# Streamlit configuration for Databricks deployment

[server]
# Enable CORS for iframe embedding in Databricks
enableCORS = true
enableXsrfProtection = true

# Server settings
port = 8501
headless = true

# File watcher settings (disable for production)
fileWatcherType = "none"

[browser]
# Don't automatically open browser (Databricks will handle this)
gatherUsageStats = false
serverAddress = "0.0.0.0"

[client]
# Show error details
showErrorDetails = true

[theme]
# Custom theme matching your design
primaryColor = "#8400FF"
backgroundColor = "#FCFCFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F2937"
font = "sans serif"

[runner]
# Improve performance
fastReruns = true
